name: Update Documentation

on:
  push:
    branches:
      - master
  issue_comment:
    types: [created]

jobs:
  update_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run documentation update script
        run: |
          python3 src/gpt-scripts/update_docs.py  # Custom Python script that uses the GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: Commit and push changes
        ### Don't need to do this - the update_docs.py makes changes directly to github
        #run: |
        #  git config --global user.name "github-actions"
        #  git config --global user.email "github-actions@github.com"
        #  git add docs/*
        # git commit -m "Automated documentation update"
        #  git push